GET http://localhost:3000/package

###

GET http://localhost:3000/

###

POST http://localhost:3000/package
Content-Type: application/json

{
    "Content": "This is a test",
    "URL": "https://github.com/winstonjs/winston",
    "JSProgram": "console.log('Hello World')"
}

###

PUT http://localhost:3000/authenticate
Content-Type: application/json

{
    "User": {
        "name": "test name",
        "isAdmin": true
    },
    "Secret": {
        "password": "test password"
    }
}

###

GET http://localhost:3000/package/byName/testName
