GET http://localhost:3000/package

###

GET http://localhost:3000/

###

POST http://localhost:3000/package
Content-Type: application/json

{
    "Content": "This is a test",
    "URL": "https://github.com/winstonjs/winston",
    "JSProgram": "console.log('Hello World')"
}

###

PUT http://localhost:3000/authenticate
Content-Type: application/json

{
    "User": {
        "name": "test name",
        "isAdmin": true
    },
    "Secret": {
        "password": "test password"
    }
}

###

GET http://localhost:3000/package/byName/testName

###

DELETE http://localhost:3000/package/byName/testName

###

POST http://localhost:3000/packages
Content-Type: application/json

{
    "Name": "name of package",
    "Version": "version of package"
}

###

GET http://localhost:3000/package/4/rate

###

DELETE http://localhost:3000/reset
X-Authorization: "ur mom"

###

GET http://localhost:3000/package/5
X-Authorization: ur dad

###

PUT http://localhost:3000/package/5
X-Authorization: ur dad
Content-Type: application/json

{
    "metadata": {
        "Name": "test",
        "Version": "1.0.0",
        "ID": "1234"
    },
    "data": {
        "Content": "test content",
        "URL": "test url",
        "JSProgram": "test js program"
    }
}

###

DELETE http://localhost:3000/package/5
X-Authorization: ur brotha

###

POST http://localhost:3000/package/byRegEx/.*test.*?rate
X-Authorization: ur sistah
Content-Type: application/json

{
    "PackageRegEx": ".*test.*?rate"
}