/**
 * 
 * ECE 461 - Spring 2023 - Project 2
 * 
 * 
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 * 
 * Version: 2.0.0
 * Contact: davisjam@purdue.edu
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// default_api

export default {
    Query: {

        // @return PackageHistoryEntry
        PackageByNameGet: ($name, $xAuthorization) => {
            return {
                "name": "Underscore",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

        // @return PackageRating
        PackageRate: ($Id_, $xAuthorization) => {
            return {
                "Id_": "Id__example",
                "xAuthorization": "xAuthorization_example"
            };
        },

        // @return Package
        PackageRetrieve: ($Id_, $xAuthorization) => {
            return {
                "Id_": "Id__example",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

    },

    Mutation: {

        // @return String!
        CreateAuthToken: ($authenticationRequest) => {
            return {
                "authenticationRequest": ""
            };
        },

        // @return 
        PackageByNameDelete: ($name, $xAuthorization) => {
            return {
                "name": "name_example",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

        // @return PackageMetadata
        PackageByRegExGet: ($regex, $body, $xAuthorization) => {
            return {
                "regex": ".*Underscore.*",
                "body": "body_example",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

        // @return Package
        PackageCreate: ($xAuthorization, $packageData) => {
            return {
                "xAuthorization": "xAuthorization_example",
                "packageData": ""
            };
        },

        // @return 
        PackageDelete: ($Id_, $xAuthorization) => {
            return {
                "Id_": "Id__example",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

        // @return 
        PackageUpdate: ($Id_, $package, $xAuthorization) => {
            return {
                "Id_": "Id__example",
                "package": "",
                "xAuthorization": "bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
            };
        },

        // @return PackageMetadata
        PackagesList: ($packageQuery, $xAuthorization, $offset) => {
            return {
                "packageQuery": "",
                "xAuthorization": "xAuthorization_example",
                "offset": "offset_example"
            };
        },

        // @return 
        RegistryReset: ($xAuthorization) => {
            return {
                "xAuthorization": "xAuthorization_example"
            };
        },

    }
}