/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import mongoose from "mongoose";
import { User, UserSchema } from "./user";
import {
  UserAuthenticationInfo,
  UserAuthenticationInfoSchema,
} from "./userAuthenticationInfo";

/**
 *
 */
export interface AuthenticationRequest {
  User: User;
  Secret: UserAuthenticationInfo;
}

export const AuthenticationRequestSchema: mongoose.Schema<AuthenticationRequest> =
  new mongoose.Schema<AuthenticationRequest>({
    User: { type: UserSchema, required: true },
    Secret: { type: UserAuthenticationInfoSchema, required: true },
  });

export const AuthenticationRequestModel = mongoose.model(
  "AuthenticationRequest",
  AuthenticationRequestSchema
);
