/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import mongoose from "mongoose";


export interface Error { 
    code: number;
    message: string;
}

export const ErrorSchema: mongoose.Schema<Error> = new mongoose.Schema<Error>({
    code: { type: Number, required: true },
    message: { type: String, required: true },
});

export const ErrorModel = mongoose.model<Error>("Error", ErrorSchema);
