/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PackageMetadata, PackageMetadataSchema } from "./packageMetadata";
import { PackageData, PackageDataSchema } from "./packageData";
import mongoose from "mongoose";
import { transform } from "./transform";

export interface Package {
  metadata: PackageMetadata;
  data: PackageData;
}

export const PackageSchema: mongoose.Schema<Package> =
  new mongoose.Schema<Package>({
    metadata: { type: PackageMetadataSchema, required: true },
    data: { type: PackageDataSchema, required: true },
  });

PackageSchema.set("toObject", { transform });

export const PackageModel = mongoose.model("package", PackageSchema);
