/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import mongoose from "mongoose";

/**
 * Authentication info for a user
 */
export interface UserAuthenticationInfo {
  /**
   * Password for a user. Per the spec, this should be a \"strong\" password.
   */
  password: string;
}


export const UserAuthenticationInfoSchema: mongoose.Schema<UserAuthenticationInfo> = new mongoose.Schema<UserAuthenticationInfo>({
    password: { type: String, required: true },
});

export const UserAuthenticationInfoModel = mongoose.model<UserAuthenticationInfo>("UserAuthenticationInfo", UserAuthenticationInfoSchema);
export const authorize: mongoose.Schema<UserAuthenticationInfo> =
  new mongoose.Schema<UserAuthenticationInfo>({
    password: { type: String, required: true },
  });
  
  
