GET http://localhost:3000/package

###

GET http://localhost:3000/

###

POST http://localhost:3000/package
Content-Type: application/json

{
    "Content": "This is a test",
    "URL": "https://github.com/winstonjs/winston",
    "JSProgram": "console.log('Hello World')"
}

###

PUT http://localhost:3000/authenticate
Content-Type: application/json

{
    "User": {
        "name": "test name",
        "isAdmin": true,
        "isUpload": false,
        "isDownload": true, 
        "isSearch": false
    },
    "Secret": {
        "password": "ur mom"
    }
}

###

GET http://localhost:3000/package/byName/testName

###

DELETE http://localhost:3000/package/byName/testName

###

POST http://localhost:3000/packages
Content-Type: application/json

{
    "Name": "name of package",
    "Version": "version of package"
}

###

GET http://localhost:3000/package/4/rate

###

DELETE http://localhost:3000/reset
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IlVzZXIiOnsibmFtZSI6InRlc3QgbmFtZSIsImlzQWRtaW4iOnRydWUsImlzVXBsb2FkIjpmYWxzZSwiaXNEb3dubG9hZCI6dHJ1ZSwiaXNTZWFyY2giOmZhbHNlfSwiU2VjcmV0Ijp7InBhc3N3b3JkIjoidXIgbW9tIn19LCJpYXQiOjE2ODE1MjMzODEsImV4cCI6MTY4MTU1OTM4MX0.VldgL74-uTMT4WTDBkpBt_Sss5LZevzVUfncjakO9kY

GET http://localhost:3000/package/5
X-Authorization: ur dad

###

PUT http://localhost:3000/package/5
X-Authorization: ur dad
Content-Type: application/json

{
    "metadata": {
        "Name": "test",
        "Version": "1.0.0",
        "ID": "1234"
    },
    "data": {
        "Content": "test content",
        "URL": "test url",
        "JSProgram": "test js program"
    }
}

###

DELETE http://localhost:3000/package/5
X-Authorization: ur brotha

###

POST http://localhost:3000/package/byRegEx/.*test.*?rate
X-Authorization: ur sistah
Content-Type: application/json

{
    "PackageRegEx": ".*test.*?rate"
}

###

POST http://localhost:3000/user
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IlVzZXIiOnsibmFtZSI6InRlc3QgbmFtZSIsImlzQWRtaW4iOnRydWUsImlzVXBsb2FkIjpmYWxzZSwiaXNEb3dubG9hZCI6dHJ1ZSwiaXNTZWFyY2giOmZhbHNlfSwiU2VjcmV0Ijp7InBhc3N3b3JkIjoidXIgbW9tIn19LCJpYXQiOjE2ODE1MjMzODEsImV4cCI6MTY4MTU1OTM4MX0.VldgL74-uTMT4WTDBkpBt_Sss5LZevzVUfncjakO9kY
Content-Type: application/json

{
        "User": {
        "name": "ur_mom",
        "isAdmin": true,
        "isUpload": false,
        "isDownload": true, 
        "isSearch": false
    },
    "Secret": {
        "password": "ece"
    }
}

###

DELETE http://localhost:3000/user
X-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7IlVzZXIiOnsibmFtZSI6InRlc3QgbmFtZSIsImlzQWRtaW4iOnRydWUsImlzVXBsb2FkIjpmYWxzZSwiaXNEb3dubG9hZCI6dHJ1ZSwiaXNTZWFyY2giOmZhbHNlfSwiU2VjcmV0Ijp7InBhc3N3b3JkIjoidXIgbW9tIn19LCJpYXQiOjE2ODE1MjMzODEsImV4cCI6MTY4MTU1OTM4MX0.VldgL74-uTMT4WTDBkpBt_Sss5LZevzVUfncjakO9kY
Content-Type: application/json

{
        "User": {
        "name": "ur_mom",
        "isAdmin": true,
        "isUpload": false,
        "isDownload": true, 
        "isSearch": false
    },
    "Secret": {
        "password": "ece"
    }
}