# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PackageQuery(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version=None, name=None):  # noqa: E501
        """PackageQuery - a model defined in OpenAPI

        :param version: The version of this PackageQuery.  # noqa: E501
        :type version: str
        :param name: The name of this PackageQuery.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'version': str,
            'name': str
        }

        self.attribute_map = {
            'version': 'Version',
            'name': 'Name'
        }

        self._version = version
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'PackageQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageQuery of this PackageQuery.  # noqa: E501
        :rtype: PackageQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self):
        """Gets the version of this PackageQuery.

          # noqa: E501

        :return: The version of this PackageQuery.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PackageQuery.

          # noqa: E501

        :param version: The version of this PackageQuery.
        :type version: str
        """

        self._version = version

    @property
    def name(self):
        """Gets the name of this PackageQuery.

        Name of a package.  - Names should only use typical \"keyboard\" characters. - The name \"*\" is reserved. See the `/packages` API for its meaning.  # noqa: E501

        :return: The name of this PackageQuery.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PackageQuery.

        Name of a package.  - Names should only use typical \"keyboard\" characters. - The name \"*\" is reserved. See the `/packages` API for its meaning.  # noqa: E501

        :param name: The name of this PackageQuery.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
