# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UserAuthenticationInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, password=None):  # noqa: E501
        """UserAuthenticationInfo - a model defined in OpenAPI

        :param password: The password of this UserAuthenticationInfo.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'password': str
        }

        self.attribute_map = {
            'password': 'password'
        }

        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'UserAuthenticationInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserAuthenticationInfo of this UserAuthenticationInfo.  # noqa: E501
        :rtype: UserAuthenticationInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def password(self):
        """Gets the password of this UserAuthenticationInfo.

        Password for a user. Per the spec, this should be a \"strong\" password.  # noqa: E501

        :return: The password of this UserAuthenticationInfo.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserAuthenticationInfo.

        Password for a user. Per the spec, this should be a \"strong\" password.  # noqa: E501

        :param password: The password of this UserAuthenticationInfo.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
