/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { User } from './user';
import { UserAuthenticationInfo } from './userAuthenticationInfo';

/**
* 
*/
export class AuthenticationRequest {
    'user': User;
    'secret': UserAuthenticationInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "User",
            "type": "User"
        },
        {
            "name": "secret",
            "baseName": "Secret",
            "type": "UserAuthenticationInfo"
        }    ];

    static getAttributeTypeMap() {
        return AuthenticationRequest.attributeTypeMap;
    }
}

