/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PackageData } from './packageData';
import { PackageMetadata } from './packageMetadata';

export class Package {
    'metadata': PackageMetadata;
    'data': PackageData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "PackageMetadata"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "PackageData"
        }    ];

    static getAttributeTypeMap() {
        return Package.attributeTypeMap;
    }
}

