/**
 * ECE 461 - Spring 2023 - Project 2
 * API for ECE 461/Spring 2023/Project 2: A Trustworthy Module Registry
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: davisjam@purdue.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PackageMetadata } from './packageMetadata';
import { User } from './user';

/**
* One entry of the history of this package.
*/
export class PackageHistoryEntry {
    'user': User;
    /**
    * Date of activity.
    */
    'date': Date;
    'packageMetadata': PackageMetadata;
    /**
    * 
    */
    'action': PackageHistoryEntry.ActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "user",
            "baseName": "User",
            "type": "User"
        },
        {
            "name": "date",
            "baseName": "Date",
            "type": "Date"
        },
        {
            "name": "packageMetadata",
            "baseName": "PackageMetadata",
            "type": "PackageMetadata"
        },
        {
            "name": "action",
            "baseName": "Action",
            "type": "PackageHistoryEntry.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return PackageHistoryEntry.attributeTypeMap;
    }
}

export namespace PackageHistoryEntry {
    export enum ActionEnum {
        Create = <any> 'CREATE',
        Update = <any> 'UPDATE',
        Download = <any> 'DOWNLOAD',
        Rate = <any> 'RATE'
    }
}
