name: Build/Test Project

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Install cloc
      run: |
        sudo apt-get update
        sudo apt-get install cloc -y

    - name: Build
      run: tsc

    - name: Test
      run: |
        # Add your test command here (e.g., npm test)
        
    - name: Start API
      run: |
        node dist/api/app.js &
        
    - name: Run API tests
      run: | 
        # Add your API test command here (e.g., npm run apitest)
      
    - name: Kill API
      run: pkill -f 'node dist/api/app.js'
        
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: SSH Keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYSSH_KEY }}
        
      - name: Deployment
        run: ssh ECE461@34.30.211.162 'cd ece461-project-part2 && git pull origin main'
