name: Build/Test Project

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: |
        chmod +x ./run
        ./run install

    - name: Install dev dependencies
      run: npm install 
      
    - name: Install stupid dependencies
      run: |
        npm install
        npm install axios
        npm install ts-node
        npm install @types/axios
        npm install @types/node
        npm install @types/jest
        npm install @types/mocha
      
    - name: Install cloc
      run: |
        sudo apt-get update
        sudo apt-get install cloc -y
      
    - name: Install Test Dependencies
      run: |
        npm install --save-dev @types/jest @types/mocha @angular/router


#     - name: TypeScript Lint
#       run: npm run lint
    
    - name: Build
      run: |
        chmod +x ./run
        ./run build

    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        chmod +x ./run
        ./run Test.txt
        
    - name: Start API
      run: ts-node src/api/app.ts &
        
    - name: Compile API tests
      run: | 
           tsc testing/apitests.ts
           node testing/apitests.js

    - name: Compile and Run for API tests
      run: node testing/apitests.js
      
    - name: Kill API
      run: pkill -f 'ts-node src/api/app.ts'
        
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: SSH Keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYSSH_KEY }}
        
      - name: Deployment
        run: ssh ECE461@34.30.211.162 'cd ece461-project-part2 && git pull origin main'
