name: Build/Test Project

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          chmod +x ./run
          ./run install
          npm install --save-dev ts-jest @types/jest @angular/router typescript@4.5.4
          npm install axios ts-node @types/axios @types/node winston @types/winston --save

      - name: Linter
        run: npm run lint

#      - name: Build
#        run: |
#          chmod +x ./run
#          ./run build
#          echo "Contents of dist directory:"
#          ls -al dist
#          ./run testing/part1test.txt
          
      - name: Set MongoDB Env Vars and Start API
        env:
          MONGODB_USERNAME: brian
          MONGODB_PASSWORD: 64ba20XbTNElNJPw
        run: |
          echo Environment variables for MongoDB set. Username is $MONGODB_USERNAME
          npx ts-node src/app.ts &

      - name: Comprehensive API Endpoint Tests
        run: npm test -- --verbose --testPathPattern=testing/comprehensiveendpoints.test.ts

      - name: Find and Kill API Process
        run: |
          ps aux | grep 'ts-node src/api/app.ts' | grep -v grep | awk '{print $2}' | xargs -r kill

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYSSH_KEY }}

      - name: Deployment
        run: ssh ECE461@34.30.211.162 'cd ece461-project-part2 && git pull origin main'
