name: Build/Test Project

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: |
        chmod +x ./run
        ./run install

    - name: Install cloc
      run: |
        sudo apt-get update
        sudo apt-get install cloc -y

    - name: Build
      run: |
        chmod +x ./run
        ./run build

    - name: Test
      run: |
        chmod +x ./run
        ./run Test.txt
