name: Snyk Security Scan

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Snyk
      run: |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
        sudo apt-get install -y nodejs
        sudo npm install -g snyk

    - name: Authenticate with Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk security scan
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test --json > snyk-results.json

    - name: Upload Snyk results to Snyk
      if: always()
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      uses: snyk/actions/upload-snyk-sarif@v1
      with:
        sarif_file: snyk-results.json
        snyk_token: ${{ secrets.SNYK_TOKEN }}
